name: Excel Check & Slack Notification

on:
  workflow_dispatch:
  schedule:
    - cron: '30 05 * * *'  # 必要なら定期実行

jobs:
  run-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv dependency manager
        run: |
          pip install uv

      - name: Run Excel check script with uv
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
          SHARED_DRIVE_ID: ${{ secrets.SHARED_DRIVE_ID }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: uv run check_excel.py
